### PR TITLE
Build with fakeroot support 

### PR DESCRIPTION
**Pull request by sulincix**

### CODE REVIEW

**Comment by Zaryob** [comment]
Processing changes...

**Comment by Zaryob** [comment]
Looked up comment:
1: Needs more works on it. Because some of process uses different command. All steps are not uses `shelltools.system()` command as well
2: Sandboxing isn't work well because of as reported belong to comment.
3: Fakerooting is cause some problems in some sources.

**Comment by paledega** [comment]
all build commands using sheltools.system()
but creating link or directories not using
I think we need fakeroot for this:
we cannot create file owned by root. or build system cannot create fifo or mknod

**Comment by paledega** [comment]
Archlinux makepkg uses fakeroot

**Comment by Zaryob** [comment]
eee sikicem ama haaa. Colorize kısmını bunun üzerine mi atarsın amq.

**Comment by paledega** [comment]
kanka kazara oldu kusura bakma :D

**Comment by paledega** [comment]
colorize bu yaptığım değişiklik ile hem daha kullanışlı oldu hemde vte daha hızlı görüntüleyebiliyor. Önceden olmayan özellikler ve vt100e tam uyumluluk geldi.

Bunu KESINLIKLE eklemeliyiz

**Comment by Zaryob** [comment]
@sulincix is it really necessary

**Pull request closed without merging**
